#!/bin/bash

backup_file() {
    if [ -d $1 ]; then
        cp $1 /home/$USER/tmp
    fi
}

# To be safe...
if [ ! -d "/home/$USER/tmp" ]; then
    mkdir /home/$USER/tmp
fi

backup_file /home/$USER/.bashrc
backup_file /home/$USER/.bash_aliases
backup_file /home/$USER/.bash_fns
backup_file /home/$USER/.config/sublime-text-3/Packages/User/Anaconda.sublime-settings
backup_file /home/$USER/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
backup_file /home/$USER/.tmux.conf

echo "Old files have been backed up to ~/tmp folder."

# Bash setup.
cp config/bashrc /home/$USER/.bashrc
cp config/bash_aliases /home/$USER/.bash_aliases
cp config/bash_fns /home/$USER/.bash_fns

# Sublime Preferences.
cp config/Anaconda.sublime-settings /home/$USER/.config/sublime-text-3/Packages/User/Anaconda.sublime-settings
cp config/Preferences.sublime-settings /home/$USER/.config/sublime-text-3/Packages/User/Preferences.sublime-settings

# Tmux setup.
cp config/tmux.conf /home/$USER/.tmux.conf

# Apply changes to bash.
source /home/$USER/.bashrc

echo "Changes applied."
