#!/bin/bash

INSTALL_DIR=/home/$USER/desktop_setup/backup

backup_file() {
    if [ -f $1 ]; then
        cp $1 /home/$USER/tmp
    fi
}

# To be safe...
if [ ! -d "/home/$USER/tmp" ]; then
    mkdir /home/$USER/tmp
fi

backup_file /home/$USER/.bashrc
backup_file /home/$USER/.config/sublime-text-3/Packages/User/Anaconda.sublime-settings
backup_file /home/$USER/.config/sublime-text-3/Packages/User/Preferences.sublime-settings

echo "Old files have been backed up to ~/tmp folder."

# Bash setup.
ln -sf $INSTALL_DIR/config/bashrc /home/$USER/.bashrc

# Sublime Preferences.
ln -sf $INSTALL_DIR/config/Anaconda.sublime-settings /home/$USER/.config/sublime-text-3/Packages/User/Anaconda.sublime-settings
ln -sf $INSTALL_DIR/config/Preferences.sublime-settings /home/$USER/.config/sublime-text-3/Packages/User/Preferences.sublime-settings

# Apply changes to bash.
source /home/$USER/.bashrc

echo "Changes applied."
