#!/bin/bash

echo "Setting up new machine!"
echo

# Update new machine.
echo "Preliminary update..."
sudo apt-get update
sudo apt-get upgrade -y

# Make tmp dir for installs.
mkdir /home/$USER/tmp

# Install Google Chrome
echo "Installing Google Chrome..."
cd /home/$USER/tmp
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

# Setup SSH keys...
ssh-keygen

# Now setup keys in Github
echo "Copy this key and add it to Github Settings:"
echo
cat /home/$USER/.ssh/id_rsa.pub
echo

read -p "Press enter when done..."

echo
echo "Cloning backup..."

# Make some folders...
mkdir /home/$USER/packages
mkdir /home/$USER/progress
mkdir /home/$USER/git

cd /home/$USER/git
git clone git@github.com:janapavlasek/backup.git

# Sublime text preliminaries
cd /home/$USER/tmp
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

# Pinta preliminaries
sudo add-apt-repository ppa:pinta-maintainers/pinta-stable

# Kdenlive preliminaries
sudo add-apt-repository ppa:kdenlive/kdenlive-stable

# Install apt-get deps.
echo "Installing apt and pip deps..."
echo
sudo apt-get update
cd /home/$USER/git/backup
sudo apt-get install -y $(grep -vE "^\s*#" install/apt_deps.txt  | tr "\n" " ")

# Install pip deps.
sudo pip install --upgrade pip
pip install -r install/pip_deps.txt

# ROS install preliminaries
echo "Installing ROS..."
echo
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
sudo apt-get update
sudo apt-get install -y ros-melodic-desktop-full

# Copy configs
echo "Setting up configs..."
echo
./home/$USER/git/backup/cp_config

# Done and sublime instructions.
echo "Your machine is set up! To install package control in sublime, do"
echo "Ctrl + \` and copy this:"
echo
cat /home/$USER/git/backup/install/pkg_ctrl.txt
echo
echo "Then install these packages:"
echo
cat /home/$USER/git/backup/sublime-packages.txt
