#!/bin/bash

mkdir_check() {
    if [ ! -d "$1" ]; then
        mkdir $1
    fi
}

EMAIL="jbpavlasek@gmail.com"
NAME="Jana Pavlasek"

# Exit when any command fails
set -e

echo "Setting up new 18.04 machine!"
echo

# Update new machine.
echo "Preliminary update..."
sudo apt update
sudo apt upgrade -y
sudo apt dist-upgrade -y

# Make tmp dir for installs.
mkdir_check /home/$USER/tmp

# Install Google Chrome
echo "Installing Google Chrome..."
cd /home/$USER/tmp
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

# Setup SSH keys...
if [ ! -d "/home/$USER/.ssh/id_rsa.pub" ]; then
    ssh-keygen
fi

# Now setup keys in Github
echo "Copy this key and add it to Github Settings:"
echo
cat /home/$USER/.ssh/id_rsa.pub
echo

read -p "Press enter when done..."

sudo apt install -y git

# Setup git
git config --global user.email $EMAIL
git config --global user.name $NAME

# Make some folders...
mkdir_check /home/$USER/packages
mkdir_check /home/$USER/progress
mkdir_check /home/$USER/git

# Clone into backup repo.
if [ ! -d "/home/$USER/git/backup" ]; then
    echo
    echo "Cloning backup..."
    cd /home/$USER/git
    git clone git@github.com:janapavlasek/backup.git
    echo
fi

# Sublime text preliminaries
cd /home/$USER/tmp
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

# Catkin tools preliminaries
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | sudo apt-key add -

# Kdenlive preliminaries
sudo add-apt-repository ppa:kdenlive/kdenlive-stable

# Install apt deps.
echo
echo "Installing apt deps..."
echo
sudo apt update
cd /home/$USER/git/backup
sudo apt install -y $(grep -vE "^\s*#" install/apt_deps.txt  | tr "\n" " ")

# Install pip deps.
echo
echo "Installing pip deps..."
echo
sudo pip install --upgrade pip
sudo pip install -r install/pip_deps.txt

echo
echo "Installing pip deps for Python 3.6..."
echo
sudo pip3 install --upgrade pip
sudo pip3 install -r install/pip_deps.txt

# ROS install preliminaries
echo
echo "Installing ROS..."
echo
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
sudo apt update
sudo apt install -y ros-melodic-desktop-full

# Copy configs
echo
echo "Setting up configs..."
echo
cd /home/$USER/git/backup/
./cp_config
source /home/$USER/.bashrc

# Done and sublime instructions.
echo
echo "Your machine is set up! To install package control in sublime, do"
echo "Ctrl + \` and copy this:"
echo
cat /home/$USER/git/backup/install/pkg_ctrl.txt
echo
echo "Then install these packages:"
echo
cat /home/$USER/git/backup/sublime-packages.txt
echo
