# ALIASES
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# WORKSPACES
alias ros-progess-ws="source /home/$USER/progress/ros/devel/setup.bash"

# ROS MASTERS
alias local-master="export ROS_MASTER_URI=http://localhost:11311"

